---

- name: If the target host runs Ubuntu, set up required repositories for virt-install package
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ vm_host_repos_ubuntu }}"
  when: ansible_distribution == 'Ubuntu'

- name: Installing Libvirt Packages and Depedencies
  package:
     name: "{{ packages[ansible_distribution] }}"
     state: present
  notify:
    - start libvirtd

- name: Setting up vm_host Networking
  import_tasks:
    net_config.yml

- name: Running Handlers
  meta: flush_handlers
