---

- name: Parse VMs File and Set Facts according to the user's Variables in /vars/ and if variables are undefined in /defaults/
  include_tasks: set_facts.yml

- name: Begin Disk related tasks such as moving pre-existing disks and creating VMs directories
  include_tasks: disk_setup.yml

- name: Begin boot related tasks such as ISO image download or move, extract etc. 
  include_tasks:  boot_image_setup.yml

- name: Invoking Virt-install commands on the Target to define new vms according to the file
  include_tasks: invoke_virt-install.yml
