---
# These two tasks create and set the facts regarding the user's defines in vars/main.yml file.
# The first command creates a dictionary with several key,value sets that will be used on the next playbooks.
# The facts that are set here are the resulting dictionaries of the template files set_facts.j2 and set_commands.j2
#
# Facts returned:
# cdrom_args      contains the user entries in each VM cdrom argument.
# set disk_args   contains the user entries in each VM disks argument.
# set urls        contains any urls found as a cdrom argument. It will be used to download iso images.
# dirs            contains the absolute paths of the directories where each VM stores its Disks.
# boot_images     contains the absolute paths of the iso images that will be used in VMs cdrom argument.
# compressed      contains any downloaded image that is compressed. decompress.py handles this list's items.
# remote_isos     contains any .iso filenames that have been placed manually by the user in the role's file folder.
# existing_disks  contains any existing disks that the VM will use. The disk file must be present in the files folder.
# boot_select     contains key,value pairs of each vm and its bootimage that will be used in the resulted command.
# args            contains all the above variables.
# cmds            contains the virt-install commands to be invoked on the target host.
#

- name: Reading the vars/main.yml File and Setting the VM facts
  set_fact:
    args: "{{ lookup('template', 'set_facts.j2') }}"

- name: Setting the list fact of the virt-install commands to be invoked on the target host
  set_fact:
    cmds: "{{ lookup('template', 'set_commands.j2') }}"

- name: The Following facts were set
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ args }}"
    - "{{ cmds }}"
