---


- name: 'Destroy VMs'
  shell: status=$(virsh domstate "{{item.name}}") && if [ "$status" == "running" ]; then (virsh destroy "{{item.name}}"); fi
  with_items: "{{vms.values()}}"
  register: result
  args:
    executable: /bin/bash

- name: debug
  debug:
    msg: "{{result}}"

- name: 'Undefine VMs'
  raw: " virsh undefine {{item.name}}"
  with_items: "{{vms.values()}}"
 
    
