---
dependencies: []
galaxy_info:
  author: socratesx
  description: Configure a QEMU/KVM Host with Libvirt
  license: license(GPLv3)
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - stretch
        - jessie
    - name: Ubuntu
      versions:
        - xenial
        - bionic
  galaxy_tags:
    - virtualization
    - libvirt
    - kvm
